name: Destroy Terraform

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Destroy VPC Resources
        working-directory: vpc
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Destroy RDS Resources
        working-directory: rds
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Destroy Compute Resources
        working-directory: compute
        run: |
          terraform init
          terraform destroy -auto-approve